#'gouhaowang,chazidian,jihaoba,beyaiw,chazidian,xingming,pianziweb,\\\
#guisd,gududai,138023,bole,04338888,shouji,rmbhuilv,xysjk,juzhao,\\\
#sjhcx,mshaoma,sojkan,taohaoba,fpsjk,aiqzu,taohaoma,38hp,ip138,kuaichala,\\\
#tiaohao,135cha,tiaohao,51so,yenwoop,baishicha,shoujicha,chahaoba,qeayer,aiqzu,jctnsy,\\\
#gdhaoma,danhaoma,yenwoop,stl56,bixinshui,bixinshui,\\\
#8684,tiantianxie,herowind,xy1989,135130,chanumber,jihaoba'

#white_list = [['\n        anquan.baidu.com    ']
#    , ['gd.tiaohao.com/others/...\xa0']
#    , ['https://www.gouhaowang.com/hao...\xa0']
#    , ['https://www.chazidian.com/haom...\xa0']
#    , ['https://m.jihaoba.com/haoduan/...\xa0']
#    , ['https://www.jihaoba.com/shouji...\xa0']
#    , ['https://m.jihaoba.com/haoduan/...\xa0']
#    , ['beyaiw.com/aiwdianhua/...\xa0']
#    , ['https://mip.chazidian.com/haom...\xa0']
#    , ['www.xingming.net/gujia...\xa0']
#    , ['https://www.pianziweb.com/mobi...\xa0']]
#white_list1 = ['www.guisd.com',
#               'gududai.com/c',
#               'www.138023.co',
#               'www.bole.name',
#               'www.04338888.',
#               'shouji.jiweix',
#               'www.rmbhuilv.',
#               'tool.baiwanzh',
#               'www.xysjk.com',
#               'www.juzhao.ne',
#               'www.sjhcx.com',
#               'www.mshaoma.c',
#               'sojkan.com/so',
#               'www.taohaoba.',
#               'www.fpsjk.cn/',
#               'm.aiqzu.net/m',
#               'aiqzu.net/mob',
#               'www.taohaoma.',
#               'www.38hp.com/',
#               'jx.ip138.com/',
#               'www.kuaichala',
#               'gd.tiaohao.co',
#               'www.135cha.co',
#               'www.tiaohao.c',
#               'www.51so.cc/m',
#               'yenwoop.com/h',
#               'www.baishicha',
#               'www.shoujicha',
#               'www.131313131',
#               'www.13677777.',
#               'www.chahaoba.',
#               'qeayer.com/di',
#               'www.38hp.com/',
#               'aiqzu.net/mob',
#               'm.jctnsy.com/',
#               'www.gdhaoma.c',
#               'www.danhaoma.',
#               'cn.amp.chahao',
#               'www.yenwoop.c',
#               'www.stl56.com',
#               'www.bixinshui',
#               'www.8684.cn/s',
#               'm.tiantianxie',
#               'www.herowind.',
#               'www.xy1989.co',
#               'www.135130.co',
#               'chanumber.cn/',
#               'm.jihaoba.com']
white_list=['www','m','mip','jx','gd','ads','search','ws','noads','call','so','fj','bj','en']
white_list1= ['gouhaowang',
               'kuz8',
             'chazidian',
             'jihaoba',
             'beyaiw',
             'chazidian',
             'xingming',
             'pianziweb',
			 'sjgsd',
             'guisd',
             'gududai',
             '138023',
             'bole',
             '04338888',
             'shouji',
             'rmbhuilv',
             'xysjk',
             'juzhao',
             'sjhcx',
             'mshaoma',
             'sojkan',
             'taohaoba',
             'fpsjk',
             'aiqzu',
             'taohaoma',
			 'haoma',
             '38hp',
             'ip138',
             'kuaichala',
             'tiaohao',
             '135cha',
             'tiaohao',
             '51so',
             'yenwoop',
             'baishicha',
             'shoujicha',
             'chahaoba',
             'qeayer',
             'jctnsy',
             'gdhaoma',
             'danhaoma',
             'yenwoop',
             'stl56',
             'bixinshui',
             'bixinshui',
             '8684',
             'tiantianxie',
             'herowind',
             'xy1989',
             '135130',
             'chanumber',
             'jihaoba',
             '51hao',
             'shoujichahao',
			 'rrsms',
			 'phone001',
			 'tiantianxieye',
			 '13677777',
			 'hmjx',
			 'tongmengguo',
			 'haomais',
			 'qqdna',
             'reg007',
             'chachahaoma',
             'xxruiyi',
             'wzyzlm',
             'verysource',
             'mobizc',
             '10865',
             'wzsswlkj','57cha','cqcounter','haolingba','026hao','vinwan','hn','99haoling','anxin360','mai','hepan'
			 ,'cryptofresh','13131313131','2dianying','dom','wncx','ekaing','computers-online','0551lhw','verysource']